/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhitepaperRouteImport } from './routes/whitepaper'
import { Route as TokenomicsRouteImport } from './routes/tokenomics'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as NodesRouteImport } from './routes/nodes'
import { Route as NewsroomRouteImport } from './routes/newsroom'
import { Route as LicenseRouteImport } from './routes/license'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalRiskDisclosuresRouteImport } from './routes/legal.risk-disclosures'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalConstitutionRouteImport } from './routes/legal.constitution'

const WhitepaperRoute = WhitepaperRouteImport.update({
  id: '/whitepaper',
  path: '/whitepaper',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenomicsRoute = TokenomicsRouteImport.update({
  id: '/tokenomics',
  path: '/tokenomics',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesRoute = NodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsroomRoute = NewsroomRouteImport.update({
  id: '/newsroom',
  path: '/newsroom',
  getParentRoute: () => rootRouteImport,
} as any)
const LicenseRoute = LicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRiskDisclosuresRoute = LegalRiskDisclosuresRouteImport.update({
  id: '/legal/risk-disclosures',
  path: '/legal/risk-disclosures',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalConstitutionRoute = LegalConstitutionRouteImport.update({
  id: '/legal/constitution',
  path: '/legal/constitution',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/license': typeof LicenseRoute
  '/newsroom': typeof NewsroomRoute
  '/nodes': typeof NodesRoute
  '/security': typeof SecurityRoute
  '/tokenomics': typeof TokenomicsRoute
  '/whitepaper': typeof WhitepaperRoute
  '/legal/constitution': typeof LegalConstitutionRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/risk-disclosures': typeof LegalRiskDisclosuresRoute
  '/legal/terms': typeof LegalTermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/license': typeof LicenseRoute
  '/newsroom': typeof NewsroomRoute
  '/nodes': typeof NodesRoute
  '/security': typeof SecurityRoute
  '/tokenomics': typeof TokenomicsRoute
  '/whitepaper': typeof WhitepaperRoute
  '/legal/constitution': typeof LegalConstitutionRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/risk-disclosures': typeof LegalRiskDisclosuresRoute
  '/legal/terms': typeof LegalTermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/license': typeof LicenseRoute
  '/newsroom': typeof NewsroomRoute
  '/nodes': typeof NodesRoute
  '/security': typeof SecurityRoute
  '/tokenomics': typeof TokenomicsRoute
  '/whitepaper': typeof WhitepaperRoute
  '/legal/constitution': typeof LegalConstitutionRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/risk-disclosures': typeof LegalRiskDisclosuresRoute
  '/legal/terms': typeof LegalTermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/case-studies'
    | '/contact'
    | '/developers'
    | '/license'
    | '/newsroom'
    | '/nodes'
    | '/security'
    | '/tokenomics'
    | '/whitepaper'
    | '/legal/constitution'
    | '/legal/privacy'
    | '/legal/risk-disclosures'
    | '/legal/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/case-studies'
    | '/contact'
    | '/developers'
    | '/license'
    | '/newsroom'
    | '/nodes'
    | '/security'
    | '/tokenomics'
    | '/whitepaper'
    | '/legal/constitution'
    | '/legal/privacy'
    | '/legal/risk-disclosures'
    | '/legal/terms'
  id:
    | '__root__'
    | '/'
    | '/case-studies'
    | '/contact'
    | '/developers'
    | '/license'
    | '/newsroom'
    | '/nodes'
    | '/security'
    | '/tokenomics'
    | '/whitepaper'
    | '/legal/constitution'
    | '/legal/privacy'
    | '/legal/risk-disclosures'
    | '/legal/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  DevelopersRoute: typeof DevelopersRoute
  LicenseRoute: typeof LicenseRoute
  NewsroomRoute: typeof NewsroomRoute
  NodesRoute: typeof NodesRoute
  SecurityRoute: typeof SecurityRoute
  TokenomicsRoute: typeof TokenomicsRoute
  WhitepaperRoute: typeof WhitepaperRoute
  LegalConstitutionRoute: typeof LegalConstitutionRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRiskDisclosuresRoute: typeof LegalRiskDisclosuresRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whitepaper': {
      id: '/whitepaper'
      path: '/whitepaper'
      fullPath: '/whitepaper'
      preLoaderRoute: typeof WhitepaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokenomics': {
      id: '/tokenomics'
      path: '/tokenomics'
      fullPath: '/tokenomics'
      preLoaderRoute: typeof TokenomicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes': {
      id: '/nodes'
      path: '/nodes'
      fullPath: '/nodes'
      preLoaderRoute: typeof NodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsroom': {
      id: '/newsroom'
      path: '/newsroom'
      fullPath: '/newsroom'
      preLoaderRoute: typeof NewsroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/license': {
      id: '/license'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof LicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/risk-disclosures': {
      id: '/legal/risk-disclosures'
      path: '/legal/risk-disclosures'
      fullPath: '/legal/risk-disclosures'
      preLoaderRoute: typeof LegalRiskDisclosuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/constitution': {
      id: '/legal/constitution'
      path: '/legal/constitution'
      fullPath: '/legal/constitution'
      preLoaderRoute: typeof LegalConstitutionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  DevelopersRoute: DevelopersRoute,
  LicenseRoute: LicenseRoute,
  NewsroomRoute: NewsroomRoute,
  NodesRoute: NodesRoute,
  SecurityRoute: SecurityRoute,
  TokenomicsRoute: TokenomicsRoute,
  WhitepaperRoute: WhitepaperRoute,
  LegalConstitutionRoute: LegalConstitutionRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRiskDisclosuresRoute: LegalRiskDisclosuresRoute,
  LegalTermsRoute: LegalTermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
